
name: API-Tourguide-CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs: 
  project-build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven 
    - name: Install Maven dependencies
      run: |
         mvn install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar 
         mvn install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar 
         mvn install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar 
             
    - name: Build with Maven
      run: mvn -B -DskipTests package --file pom.xml
     
    - name: Run tests
      run: mvn --batch-mode --update-snapshots verify

      
    - name: Upload Artifact
    - uses: actions/upload-artifact@v3
      with:
         name: packaged-artifact
         path: target/*.jar  
  docker-build:
    runs-on: ubuntu-latest
    needs:
      - project-build-test
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag api-tourguide:$(date +%s)
        
 
